from __future__ import annotations

import argparse
import csv
import json
import subprocess
import time
from pathlib import Path

import lightning.pytorch as pl
import torch
import yaml
from lightning.pytorch.callbacks import (
    EarlyStopping,
    LearningRateMonitor,
    ModelCheckpoint,
)
from lightning.pytorch.loggers import CSVLogger

from eeg2qwerty.data.brain2qwerty_v1 import build_upstream_eeg_loaders
from eeg2qwerty.models import count_trainable_parameters
from eeg2qwerty.training import StandardizedM2Module


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train the standardized public EEG2Qwerty M2 baseline."
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=Path("configs/m2_whole_sentence_typed.yaml"),
    )
    parser.add_argument("--data-root", type=Path, required=True)
    parser.add_argument("--cache-root", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument(
        "--target-mode",
        choices=["typed_key", "intended"],
        default=None,
        help="Optional override of protocol.target in the YAML config.",
    )
    parser.add_argument("--num-workers", type=int, default=8)
    parser.add_argument("--debug", action="store_true")
    parser.add_argument(
        "--upstream-commit",
        default="unknown",
        help="Brain2Qwerty commit SHA used for this run.",
    )
    return parser.parse_args()


def _git_sha() -> str:
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            text=True,
        ).strip()
    except Exception:
        return "unknown"


def _metric_value(metrics, name: str):
    value = metrics.get(name)
    if value is None:
        return None
    if hasattr(value, "detach"):
        value = value.detach().cpu().item()
    return float(value)


def _hardware_name() -> str:
    if torch.cuda.is_available():
        return torch.cuda.get_device_name(0)
    return "CPU"


def _write_registry_row(
    output_dir: Path,
    *,
    config_name: str,
    commit_sha: str,
    upstream_commit_sha: str,
    target_mode: str,
    seed: int,
    parameters: int,
    peak_vram_gb: float | None,
    train_time_seconds: float,
    metrics: dict,
    debug: bool,
) -> None:
    path = output_dir / "registry_row.csv"
    fields = [
        "experiment",
        "commit_sha",
        "upstream_commit_sha",
        "protocol",
        "target",
        "evaluator",
        "seed",
        "parameters",
        "hardware",
        "peak_vram_gb",
        "train_time_seconds",
        "neural_cer",
        "participant_mean_cer",
        "participant_median_cer",
        "participant_sd_cer",
        "lm_assisted_cer",
        "status",
        "notes",
    ]
    row = {
        "experiment": config_name,
        "commit_sha": commit_sha,
        "upstream_commit_sha": upstream_commit_sha,
        "protocol": "keypress_aligned_whole_sentence",
        "target": target_mode,
        "evaluator": "eeg2qwerty_standardized_v1",
        "seed": seed,
        "parameters": parameters,
        "hardware": _hardware_name(),
        "peak_vram_gb": peak_vram_gb,
        "train_time_seconds": train_time_seconds,
        "neural_cer": metrics.get("test_pooled_CER"),
        "participant_mean_cer": metrics.get("test_CER"),
        "participant_median_cer": metrics.get("test_median_CER"),
        "participant_sd_cer": metrics.get("test_CER_std"),
        "lm_assisted_cer": "",
        "status": "debug" if debug else "candidate_reproduction",
        "notes": "Generated by scripts/train_standardized_m2.py",
    }

    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerow(row)


def main() -> None:
    args = parse_args()

    config = yaml.safe_load(args.config.read_text(encoding="utf-8"))
    protocol = config["protocol"]
    model_config = config["model"]
    training = config["training"]

    target_mode = args.target_mode or protocol["target"]
    max_typographical_errors = protocol.get("max_typographical_errors")

    seed = int(training["seed"])
    pl.seed_everything(seed, workers=True)
    torch.set_float32_matmul_precision("high")

    args.output_dir.mkdir(parents=True, exist_ok=True)

    loaders, events = build_upstream_eeg_loaders(
        data_root=args.data_root.expanduser().resolve(),
        cache_root=args.cache_root.expanduser().resolve(),
        train_batch_keystrokes=int(training.get("train_batch_keystrokes", 256)),
        eval_batch_keystrokes=int(training.get("eval_batch_keystrokes", 512)),
        num_workers=args.num_workers,
        seed=seed,
        debug=args.debug,
        max_typographical_errors=max_typographical_errors,
    )

    required = {"train", "val", "test"}
    missing = required - set(loaders)
    if missing:
        raise RuntimeError(f"Missing required split loaders: {sorted(missing)}")

    first_batch = next(iter(loaders["train"]))
    n_channels = int(first_batch.data["neuro"].shape[1])

    module = StandardizedM2Module(
        n_channels=n_channels,
        target_mode=target_mode,
        width=int(model_config["width"]),
        encoder_blocks=int(model_config["encoder_blocks"]),
        transformer_layers=int(model_config["transformer_layers"]),
        transformer_heads=int(model_config["transformer_heads"]),
        transformer_ff=int(model_config["transformer_ff"]),
        encoder_dropout=float(model_config["encoder_dropout"]),
        transformer_dropout=float(model_config["transformer_dropout"]),
        learning_rate=float(training["learning_rate"]),
        weight_decay=float(training["weight_decay"]),
    )
    parameters = count_trainable_parameters(module.model)

    cer_checkpoint = ModelCheckpoint(
        dirpath=args.output_dir,
        filename="best-cer",
        monitor="val_CER",
        mode="min",
        save_top_k=1,
        save_last=True,
    )
    loss_checkpoint = ModelCheckpoint(
        dirpath=args.output_dir,
        filename="best-loss",
        monitor="val_loss",
        mode="min",
        save_top_k=1,
        save_last=False,
    )
    early_stopping = EarlyStopping(
        monitor="val_CER",
        mode="min",
        patience=int(training.get("patience", 12)),
    )

    logger = CSVLogger(save_dir=args.output_dir, name="logs")

    accelerator = "gpu" if torch.cuda.is_available() else "cpu"
    precision = "bf16-mixed" if accelerator == "gpu" else "32-true"

    trainer = pl.Trainer(
        accelerator=accelerator,
        devices=1,
        precision=precision,
        max_epochs=int(training["epochs"]),
        gradient_clip_val=float(training.get("gradient_clip", 1.0)),
        callbacks=[
            cer_checkpoint,
            loss_checkpoint,
            early_stopping,
            LearningRateMonitor(logging_interval="step"),
        ],
        logger=logger,
        default_root_dir=args.output_dir,
        log_every_n_steps=20,
        benchmark=(accelerator == "gpu"),
        deterministic=False,
    )

    if accelerator == "gpu":
        torch.cuda.reset_peak_memory_stats()

    started = time.perf_counter()
    trainer.fit(
        module,
        train_dataloaders=loaders["train"],
        val_dataloaders=loaders["val"],
    )
    trainer.test(
        module,
        dataloaders=loaders["test"],
        ckpt_path="best",
    )
    elapsed = time.perf_counter() - started

    peak_vram_gb = None
    if accelerator == "gpu":
        peak_vram_gb = torch.cuda.max_memory_allocated() / (1024**3)

    callback_metrics = {
        name: _metric_value(trainer.callback_metrics, name)
        for name in (
            "test_CER",
            "test_pooled_CER",
            "test_median_CER",
            "test_CER_std",
        )
    }

    commit_sha = _git_sha()
    split_counts = {
        split: int(
            ((events["split"] == split) & (events["type"] == "Keystroke")).sum()
        )
        for split in ("train", "val", "test")
    }

    manifest = {
        "schema_version": 1,
        "experiment": config.get("name", args.config.stem),
        "status": "debug" if args.debug else "candidate_reproduction",
        "eeg2qwerty_commit": commit_sha,
        "upstream_brain2qwerty_commit": args.upstream_commit,
        "config": str(args.config),
        "target_mode": target_mode,
        "max_typographical_errors": max_typographical_errors,
        "seed": seed,
        "trainable_parameters": parameters,
        "n_channels": n_channels,
        "split_keystrokes": split_counts,
        "accelerator": accelerator,
        "hardware": _hardware_name(),
        "precision": precision,
        "peak_vram_gb": peak_vram_gb,
        "train_and_test_seconds": elapsed,
        "metrics": callback_metrics,
        "best_cer_checkpoint": cer_checkpoint.best_model_path,
        "best_loss_checkpoint": loss_checkpoint.best_model_path,
    }
    (args.output_dir / "run_summary.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    _write_registry_row(
        args.output_dir,
        config_name=str(config.get("name", args.config.stem)),
        commit_sha=commit_sha,
        upstream_commit_sha=args.upstream_commit,
        target_mode=target_mode,
        seed=seed,
        parameters=parameters,
        peak_vram_gb=peak_vram_gb,
        train_time_seconds=elapsed,
        metrics=callback_metrics,
        debug=args.debug,
    )

    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
